import Head from "next/head";
import Header from "../components/Header"
import Feed from "../components/Feed/Feed"
import Modal from "../components/Modal/Modal"

export default function Home() {
  return (
    <div className="bg-gray-50 overflow-y-scroll scrollbar-hide h-screen">
      <Head>
        <title>Instagram 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Modal />
      <Header />
      <Feed />

      
    </div>
  );
}
